/* Runtime support for Quantity values, mirroring the interpreter's own
 * unit handling (unit_factor / resolve_unit_factor / convert in
 * interpreter/mod.rs): the dimension of a quantity is a compile-time fact,
 * but its unit is a runtime string, exactly like Value::Quantity. */
typedef struct { double v; const char* u; } Qty;

/* Unit catalog: symbol, factor to the coherent SI unit and, for simple
 * atoms, their single base dimension (NULL for derived units such as J).
 * Mirrors types::unit_info. */
typedef struct { const char* s; double f; const char* base; } OstrinUnit;
static const OstrinUnit ostrin_units[] = {
    {"m", 1.0, "L"}, {"nm", 1e-9, "L"}, {"um", 1e-6, "L"}, {"mm", 1e-3, "L"}, {"cm", 0.01, "L"}, {"km", 1000.0, "L"},
    {"s", 1.0, "T"}, {"ns", 1e-9, "T"}, {"us", 1e-6, "T"}, {"ms", 1e-3, "T"}, {"min", 60.0, "T"}, {"h", 3600.0, "T"},
    {"day", 86400.0, "T"},
    {"kg", 1.0, "M"}, {"g", 1e-3, "M"}, {"mg", 1e-6, "M"}, {"ug", 1e-9, "M"},
    {"K", 1.0, "Th"}, {"A", 1.0, "I"}, {"mA", 1e-3, "I"},
    {"mol", 1.0, "N"}, {"mmol", 1e-3, "N"}, {"umol", 1e-6, "N"}, {"cd", 1.0, "J"},
    {"USD", 1.0, "$"}, {"EUR", 1.0, "$"}, {"bit", 1.0, "B"}, {"byte", 8.0, "B"},
    {"L", 1e-3, NULL}, {"mL", 1e-6, NULL}, {"Hz", 1.0, NULL}, {"kHz", 1e3, NULL},
    {"N", 1.0, NULL}, {"kN", 1e3, NULL}, {"J", 1.0, NULL}, {"kJ", 1e3, NULL}, {"cal", 4.184, NULL},
    {"kcal", 4184.0, NULL}, {"W", 1.0, NULL}, {"kW", 1e3, NULL}, {"Pa", 1.0, NULL}, {"kPa", 1e3, NULL},
    {"bar", 1e5, NULL}, {"atm", 101325.0, NULL}, {"mmHg", 133.322387415, NULL}, {"C", 1.0, NULL},
    {"V", 1.0, NULL}, {"mV", 1e-3, NULL}, {"ohm", 1.0, NULL}
};

/* Units declared by the program (`unit`/`define`), generated by codegen.rs; ends with a NULL symbol. */
static const OstrinUnit ostrin_user_units[] = {
/*@USER_UNITS@*/    {NULL, 0.0, NULL}
};

static const OstrinUnit* ostrin_unit_lookup(const char* a) {
    for (size_t i = 0; i < sizeof ostrin_units / sizeof ostrin_units[0]; i++) {
        if (strcmp(ostrin_units[i].s, a) == 0) return &ostrin_units[i];
    }
    for (size_t i = 0; ostrin_user_units[i].s; i++) {
        if (strcmp(ostrin_user_units[i].s, a) == 0) return &ostrin_user_units[i];
    }
    fprintf(stderr, "runtime error: unknown unit '%s'\n", a);
    exit(1);
}

static double ostrin_unit_pow(double base, int e) {
    double r = 1.0;
    for (int i = 0; i < (e < 0 ? -e : e); i++) r *= base;
    return e < 0 ? 1.0 / r : r;
}

#define OSTRIN_MAX_UNIT_ATOMS 16
typedef struct { const OstrinUnit* u[OSTRIN_MAX_UNIT_ATOMS]; int e[OSTRIN_MAX_UNIT_ATOMS]; int n; } OstrinUnitAtoms;

static void ostrin_unit_push(OstrinUnitAtoms* atoms, const OstrinUnit* u, int e) {
    for (int i = 0; i < atoms->n; i++) {
        if (atoms->u[i] == u) { atoms->e[i] += e; return; }
    }
    if (atoms->n == OSTRIN_MAX_UNIT_ATOMS) { fprintf(stderr, "runtime error: unit expression too long\n"); exit(1); }
    atoms->u[atoms->n] = u;
    atoms->e[atoms->n] = e;
    atoms->n++;
}

static void ostrin_unit_drop_zero(OstrinUnitAtoms* atoms) {
    int k = 0;
    for (int i = 0; i < atoms->n; i++) {
        if (atoms->e[i] != 0) { atoms->u[k] = atoms->u[i]; atoms->e[k] = atoms->e[i]; k++; }
    }
    atoms->n = k;
}

/* Parses "kg*m^2/s^2" left to right into atoms, as types::unit_atoms. */
static void ostrin_unit_parse(const char* expr, int sign_of_all, OstrinUnitAtoms* atoms) {
    if (*expr == 0) return;
    int sign = 1;
    const char* p = expr;
    for (;;) {
        char atom[64];
        size_t n = 0;
        while (*p && *p != '*' && *p != '/' && *p != '^') { if (n < 63) atom[n++] = *p; p++; }
        atom[n] = 0;
        if (n == 0) { fprintf(stderr, "runtime error: malformed unit expression '%s'\n", expr); exit(1); }
        int e = 1;
        if (*p == '^') {
            p++;
            char digits[16];
            size_t k = 0;
            while ((*p >= '0' && *p <= '9') || *p == '-') { if (k < 15) digits[k++] = *p; p++; }
            digits[k] = 0;
            e = atoi(digits);
        }
        if (strcmp(atom, "1") != 0) ostrin_unit_push(atoms, ostrin_unit_lookup(atom), sign * e * sign_of_all);
        if (*p == 0) break;
        if (*p == '*') sign = 1;
        else if (*p == '/') sign = -1;
        else { fprintf(stderr, "runtime error: malformed unit expression '%s'\n", expr); exit(1); }
        p++;
    }
    ostrin_unit_drop_zero(atoms);
}

static double ostrin_unit_expr_factor(const char* expr) {
    OstrinUnitAtoms atoms = { {0}, {0}, 0 };
    ostrin_unit_parse(expr, 1, &atoms);
    double result = 1.0;
    for (int i = 0; i < atoms.n; i++) result *= ostrin_unit_pow(atoms.u[i]->f, atoms.e[i]);
    return result;
}

static double ostrin_convert(double v, const char* from, const char* to) {
    if (strcmp(from, to) == 0) return v;
    return v * ostrin_unit_expr_factor(from) / ostrin_unit_expr_factor(to);
}

static const char* ostrin_unit_cat(const char* a, const char* op, const char* b) {
    size_t n = strlen(a) + strlen(op) + strlen(b) + 1;
    char* out = (char*)ostrin_alloc(n);
    if (!out) { fprintf(stderr, "ostrin: out of memory\n"); exit(1); }
    snprintf(out, n, "%s%s%s", a, op, b);
    return out;
}

/* Canonical product/quotient of two units (types::unit_combine): returns the
 * formatted unit and stores the value scale in *scale. */
static const char* ostrin_unit_combine(const char* a, const char* b, int divide, double* scale) {
    OstrinUnitAtoms atoms = { {0}, {0}, 0 };
    ostrin_unit_parse(a, 1, &atoms);
    OstrinUnitAtoms rhs = { {0}, {0}, 0 };
    ostrin_unit_parse(b, divide ? -1 : 1, &rhs);
    for (int i = 0; i < rhs.n; i++) ostrin_unit_push(&atoms, rhs.u[i], rhs.e[i]);
    ostrin_unit_drop_zero(&atoms);
    *scale = 1.0;
    int i = 0;
    while (i < atoms.n) {
        const char* base = atoms.u[i]->base;
        if (base) {
            double fi = atoms.u[i]->f;
            int j = i + 1;
            while (j < atoms.n) {
                if (atoms.u[j]->base && strcmp(atoms.u[j]->base, base) == 0) {
                    *scale *= ostrin_unit_pow(atoms.u[j]->f / fi, atoms.e[j]);
                    atoms.e[i] += atoms.e[j];
                    for (int k = j; k + 1 < atoms.n; k++) { atoms.u[k] = atoms.u[k + 1]; atoms.e[k] = atoms.e[k + 1]; }
                    atoms.n--;
                } else {
                    j++;
                }
            }
        }
        if (atoms.e[i] == 0) {
            for (int k = i; k + 1 < atoms.n; k++) { atoms.u[k] = atoms.u[k + 1]; atoms.e[k] = atoms.e[k + 1]; }
            atoms.n--;
        } else {
            i++;
        }
    }
    char buf[512];
    size_t len = 0;
    buf[0] = 0;
    int has_num = 0;
    for (int k = 0; k < atoms.n; k++) {
        if (atoms.e[k] <= 0) continue;
        if (atoms.e[k] == 1) len += snprintf(buf + len, sizeof buf - len, "%s%s", has_num ? "*" : "", atoms.u[k]->s);
        else len += snprintf(buf + len, sizeof buf - len, "%s%s^%d", has_num ? "*" : "", atoms.u[k]->s, atoms.e[k]);
        has_num = 1;
    }
    int has_den = 0;
    for (int k = 0; k < atoms.n; k++) if (atoms.e[k] < 0) has_den = 1;
    if (!has_num && has_den) len += snprintf(buf + len, sizeof buf - len, "1");
    for (int k = 0; k < atoms.n; k++) {
        if (atoms.e[k] >= 0) continue;
        if (atoms.e[k] == -1) len += snprintf(buf + len, sizeof buf - len, "/%s", atoms.u[k]->s);
        else len += snprintf(buf + len, sizeof buf - len, "/%s^%d", atoms.u[k]->s, -atoms.e[k]);
    }
    return ostrin_unit_cat(buf, "", "");
}

static Qty ostrin_qty_add(Qty a, Qty b) { Qty r = { a.v + ostrin_convert(b.v, b.u, a.u), a.u }; return r; }
static Qty ostrin_qty_sub(Qty a, Qty b) { Qty r = { a.v - ostrin_convert(b.v, b.u, a.u), a.u }; return r; }
static Qty ostrin_qty_mul(Qty a, Qty b) {
    double scale;
    Qty r = { a.v * b.v, ostrin_unit_combine(a.u, b.u, 0, &scale) };
    if (scale != 1.0) r.v *= scale;
    return r;
}
static Qty ostrin_qty_div(Qty a, Qty b) {
    double scale;
    Qty r = { a.v / b.v, ostrin_unit_combine(a.u, b.u, 1, &scale) };
    if (scale != 1.0) r.v *= scale;
    return r;
}
/* A product whose dimensions cancel: the leftover unit (`J/N/m`) is folded
 * into the value, as the interpreter does. */
static Qty ostrin_qty_mul_pure(Qty a, Qty b) {
    Qty r = ostrin_qty_mul(a, b);
    if (*r.u) { r.v *= ostrin_unit_expr_factor(r.u); r.u = ""; }
    return r;
}
static double ostrin_qty_ratio(Qty a, Qty b) { return a.v / ostrin_convert(b.v, b.u, a.u); }
static Qty ostrin_qty_scale_mul(Qty a, double s) { Qty r = { a.v * s, a.u }; return r; }
static Qty ostrin_qty_scale_div(Qty a, double s) { Qty r = { a.v / s, a.u }; return r; }
static Qty ostrin_scalar_div_qty(double s, Qty a) {
    double scale;
    Qty r = { s / a.v, ostrin_unit_combine("", a.u, 1, &scale) };
    return r;
}
static int ostrin_qty_cmp(Qty a, Qty b) {
    double c = ostrin_convert(b.v, b.u, a.u);
    return a.v < c ? -1 : (a.v > c ? 1 : 0);
}

static void ostrin_print_qty(Qty q) {
    char buf[64];
    ostrin_fmt_double(q.v, buf, sizeof buf);
    if (*q.u) printf("%s %s\n", buf, q.u);
    else printf("%s\n", buf);
}

static const char* ostrin_qty_to_string(Qty q) {
    char buf[64];
    ostrin_fmt_double(q.v, buf, sizeof buf);
    if (!*q.u) return ostrin_unit_cat(buf, "", "");
    return ostrin_unit_cat(ostrin_unit_cat(buf, " ", ""), q.u, "");
}

