import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = path.join(repositoryRoot, "website", "provenance-data.js");
const sourcePath = "examples/measurement_scalar.ostrin";

function expectedArtifact() {
  const raw = execFileSync("cargo", [
    "run",
    "--quiet",
    "--manifest-path",
    "compiler/Cargo.toml",
    "--",
    "--provenance-report",
    "--json",
    "--target",
    "wasm32-wasi",
    sourcePath,
  ], { cwd: repositoryRoot, encoding: "utf8" });
  return JSON.parse(raw);
}

function render(artifact) {
  return `// Generated by scripts/provenance-page.mjs. Do not edit by hand.\n` +
    `globalThis.OSTRIN_PROVENANCE = Object.freeze(${JSON.stringify(artifact, null, 2)});\n`;
}

const expected = render(expectedArtifact());
if (process.argv.includes("--write")) {
  writeFileSync(outputPath, expected, "utf8");
  console.log(`provenance-page: wrote ${path.relative(repositoryRoot, outputPath)}`);
} else if (!existsSync(outputPath) || readFileSync(outputPath, "utf8").replaceAll("\r\n", "\n") !== expected) {
  console.error("provenance-page: website/provenance-data.js is stale; run node scripts/provenance-page.mjs --write");
  process.exitCode = 1;
} else {
  console.log("provenance-page: ok");
}
