import { existsSync, readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function readRepositoryFile(relativePath) {
  const absolutePath = path.join(repositoryRoot, relativePath);
  return existsSync(absolutePath) ? readFileSync(absolutePath, "utf8") : "";
}

function filesUnder(relativePath) {
  const absolutePath = path.join(repositoryRoot, relativePath);
  if (!existsSync(absolutePath)) return [];
  return readdirSync(absolutePath, { withFileTypes: true }).flatMap((entry) => {
    const child = path.join(relativePath, entry.name);
    return entry.isDirectory() ? filesUnder(child) : [child];
  });
}

function countRustTests(relativePath) {
  return [...readRepositoryFile(relativePath).replaceAll("\r\n", "\n").matchAll(/^\s*#\[test\]\s*$/gm)].length;
}

export function collectSiteFacts() {
  const version = readRepositoryFile("compiler/Cargo.toml").match(/^version\s*=\s*"([^"]+)"/m)?.[1];
  if (!version) throw new Error("compiler/Cargo.toml: unable to determine package version");

  return {
    version,
    designDocs: String(filesUnder("docs/design").filter((file) => file.endsWith(".md")).length),
    examples: String(filesUnder("examples").filter((file) => file.endsWith(".ostrin")).length),
    integrationTests: String(countRustTests("compiler/tests/examples.rs")),
    differentialTests: String(countRustTests("compiler/tests/differential.rs")),
    unitTests: String(countRustTests("compiler/src/fmt.rs")),
  };
}

export function renderSiteData(facts) {
  return `// Generated by scripts/website-metadata.mjs. Do not edit by hand.\n` +
    `globalThis.OSTRIN_SITE_FACTS = Object.freeze(${JSON.stringify(facts, null, 2)});\n`;
}
