import { existsSync, readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function readRepositoryFile(relativePath) {
  const absolutePath = path.join(repositoryRoot, relativePath);
  return existsSync(absolutePath) ? readFileSync(absolutePath, "utf8") : "";
}

function filesUnder(relativePath) {
  const absolutePath = path.join(repositoryRoot, relativePath);
  if (!existsSync(absolutePath)) return [];
  return readdirSync(absolutePath, { withFileTypes: true }).flatMap((entry) => {
    const child = path.join(relativePath, entry.name);
    return entry.isDirectory() ? filesUnder(child) : [child];
  });
}

function countRustTests(relativePath) {
  return [...readRepositoryFile(relativePath).replaceAll("\r\n", "\n").matchAll(/^\s*#\[test\]\s*$/gm)].length;
}

export function collectSiteFacts() {
  const version = readRepositoryFile("compiler/Cargo.toml").match(/^version\s*=\s*"([^"]+)"/m)?.[1];
  if (!version) throw new Error("compiler/Cargo.toml: unable to determine package version");

  // A version counts as released only when CHANGELOG.md dates its heading and its release notes
  // exist; the website never claims a release that the repository does not record.
  const heading = readRepositoryFile("CHANGELOG.md").replaceAll("\r\n", "\n").split("\n")
    .find((line) => line.startsWith(`## ${version} `));
  const releaseDate = heading?.match(/\((\d{4}-\d{2}-\d{2})\)\s*$/)?.[1];
  const released = Boolean(releaseDate) && existsSync(path.join(repositoryRoot, "docs", "releases", `v${version}.md`));

  return {
    version,
    releaseStatus: released ? "published" : "unreleased",
    releaseDate: released ? releaseDate : "",
    releaseUrl: released ? `https://github.com/sircalch/Ostrin/releases/tag/v${version}` : "",
    designDocs: String(filesUnder("docs/design").filter((file) => file.endsWith(".md")).length),
    examples: String(filesUnder("examples").filter((file) => file.endsWith(".ostrin")).length),
    integrationTests: String(countRustTests("compiler/tests/examples.rs")),
    differentialTests: String(countRustTests("compiler/tests/differential.rs")),
    unitTests: String(countRustTests("compiler/src/fmt.rs")),
  };
}

export function renderSiteData(facts) {
  return `// Generated by scripts/website-metadata.mjs. Do not edit by hand.\n` +
    `globalThis.OSTRIN_SITE_FACTS = Object.freeze(${JSON.stringify(facts, null, 2)});\n`;
}
