// Generated by scripts/provenance-page.mjs. Do not edit by hand.
globalThis.OSTRIN_PROVENANCE = Object.freeze({
  "activity": {
    "effects": [
      "io",
      "measurement"
    ],
    "sites": [
      {
        "col": 0,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::sum",
        "line": 0,
        "operation": "measurements.length"
      },
      {
        "col": 15,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::uncertainties",
        "line": 87,
        "operation": "std.measurements::uncertainty"
      },
      {
        "col": 17,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::sum",
        "line": 101,
        "operation": "std.measurements::exact"
      },
      {
        "col": 15,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::sum",
        "line": 103,
        "operation": "std.measurements::add"
      },
      {
        "col": 13,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::mean",
        "line": 114,
        "operation": "measurements.length"
      },
      {
        "col": 11,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::mean",
        "line": 118,
        "operation": "std.measurements::sum"
      },
      {
        "col": 25,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::mean",
        "line": 119,
        "operation": "std.measurements::scale"
      },
      {
        "col": 5,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::uncertainty",
        "line": 128,
        "operation": "std.measurements::variance"
      },
      {
        "col": 11,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::summary",
        "line": 135,
        "operation": "std.measurements::uncertainty"
      },
      {
        "col": 5,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::unknown_from",
        "line": 187,
        "operation": "std.measurements::unknown"
      },
      {
        "col": 16,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::scale",
        "line": 192,
        "operation": "std.measurements::unknown_from"
      },
      {
        "col": 11,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::scale",
        "line": 194,
        "operation": "std.measurements::merge_scaled"
      },
      {
        "col": 25,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::scale",
        "line": 201,
        "operation": "std.measurements::unknown"
      },
      {
        "col": 19,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::add",
        "line": 207,
        "operation": "std.measurements::unknown_from"
      },
      {
        "col": 19,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::add",
        "line": 210,
        "operation": "std.measurements::unknown_from"
      },
      {
        "col": 11,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::add",
        "line": 212,
        "operation": "std.measurements::merge_scaled"
      },
      {
        "col": 27,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::add",
        "line": 213,
        "operation": "std.measurements::merge_scaled"
      },
      {
        "col": 19,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::sub",
        "line": 223,
        "operation": "std.measurements::unknown_from"
      },
      {
        "col": 19,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::sub",
        "line": 226,
        "operation": "std.measurements::unknown_from"
      },
      {
        "col": 11,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::sub",
        "line": 228,
        "operation": "std.measurements::merge_scaled"
      },
      {
        "col": 27,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::sub",
        "line": 229,
        "operation": "std.measurements::merge_scaled"
      },
      {
        "col": 19,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::mul",
        "line": 240,
        "operation": "std.measurements::unknown_from"
      },
      {
        "col": 11,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::mul",
        "line": 242,
        "operation": "std.measurements::merge_scaled"
      },
      {
        "col": 27,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::mul",
        "line": 243,
        "operation": "std.measurements::merge_scaled"
      },
      {
        "col": 19,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::div",
        "line": 257,
        "operation": "std.measurements::unknown_from"
      },
      {
        "col": 11,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::div",
        "line": 261,
        "operation": "std.measurements::merge_scaled"
      },
      {
        "col": 27,
        "effect": "measurement",
        "file": "<ostrin-std>/measurements.ostrin",
        "function": "std.measurements::div",
        "line": 262,
        "operation": "std.measurements::merge_scaled"
      },
      {
        "col": 0,
        "effect": "measurement",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 0,
        "operation": "std.measurements::add"
      },
      {
        "col": 0,
        "effect": "measurement",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 0,
        "operation": "std.measurements::add"
      },
      {
        "col": 0,
        "effect": "measurement",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 0,
        "operation": "std.measurements::div"
      },
      {
        "col": 0,
        "effect": "measurement",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 0,
        "operation": "std.measurements::mul"
      },
      {
        "col": 0,
        "effect": "measurement",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 0,
        "operation": "std.measurements::sub"
      },
      {
        "col": 0,
        "effect": "measurement",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 0,
        "operation": "std.measurements::summary"
      },
      {
        "col": 0,
        "effect": "measurement",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 0,
        "operation": "std.measurements::summary"
      },
      {
        "col": 0,
        "effect": "measurement",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 0,
        "operation": "std.measurements::summary"
      },
      {
        "col": 0,
        "effect": "measurement",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 0,
        "operation": "std.measurements::summary"
      },
      {
        "col": 0,
        "effect": "measurement",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 0,
        "operation": "std.measurements::summary"
      },
      {
        "col": 0,
        "effect": "measurement",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 0,
        "operation": "std.measurements::summary"
      },
      {
        "col": 0,
        "effect": "measurement",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 0,
        "operation": "std.measurements::summary"
      },
      {
        "col": 11,
        "effect": "measurement",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 5,
        "operation": "std.measurements::standard"
      },
      {
        "col": 24,
        "effect": "measurement",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 6,
        "operation": "std.measurements::standard"
      },
      {
        "col": 17,
        "effect": "io",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 8,
        "operation": "print"
      },
      {
        "col": 17,
        "effect": "io",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 9,
        "operation": "print"
      },
      {
        "col": 17,
        "effect": "io",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 10,
        "operation": "print"
      },
      {
        "col": 17,
        "effect": "io",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 11,
        "operation": "print"
      },
      {
        "col": 17,
        "effect": "io",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 12,
        "operation": "print"
      },
      {
        "col": 74,
        "effect": "measurement",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 12,
        "operation": "std.measurements::exact"
      },
      {
        "col": 17,
        "effect": "io",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 13,
        "operation": "print"
      },
      {
        "col": 17,
        "effect": "io",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 14,
        "operation": "print"
      },
      {
        "col": 59,
        "effect": "measurement",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 14,
        "operation": "std.measurements::scale"
      },
      {
        "col": 78,
        "effect": "measurement",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 14,
        "operation": "std.measurements::unknown"
      },
      {
        "col": 29,
        "effect": "io",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 16,
        "operation": "print"
      },
      {
        "col": 25,
        "effect": "io",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 18,
        "operation": "print"
      },
      {
        "col": 11,
        "effect": "measurement",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 21,
        "operation": "std.measurements::standard"
      },
      {
        "col": 18,
        "effect": "io",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 22,
        "operation": "print"
      },
      {
        "col": 25,
        "effect": "io",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 23,
        "operation": "print"
      },
      {
        "col": 11,
        "effect": "measurement",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 25,
        "operation": "std.measurements::standard"
      },
      {
        "col": 18,
        "effect": "io",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 26,
        "operation": "print"
      },
      {
        "col": 25,
        "effect": "io",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 27,
        "operation": "print"
      },
      {
        "col": 11,
        "effect": "measurement",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 29,
        "operation": "std.measurements::uncertainties"
      },
      {
        "col": 39,
        "effect": "measurement",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 29,
        "operation": "std.measurements::unknown"
      },
      {
        "col": 18,
        "effect": "io",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 30,
        "operation": "print"
      },
      {
        "col": 25,
        "effect": "io",
        "file": "examples/measurement_scalar.ostrin",
        "function": "main",
        "line": 31,
        "operation": "print"
      }
    ]
  },
  "compiler": {
    "commit": "unknown",
    "name": "ostrinc",
    "target": "wasm32-wasi",
    "version": "0.1.0"
  },
  "experimental": true,
  "inputs": [],
  "limitations": [
    "This artifact is a conservative source inventory, not a static effect guarantee.",
    "A future R2/R3 pipeline will add input snapshots, output hashes, lockfiles and runtime metadata."
  ],
  "outputs": [],
  "program": {
    "entry": "examples/measurement_scalar.ostrin",
    "source_hash": "sha256:bb8d489e7c01dcd52ac69bde14d43c244b3589d8c24f651963d3666f3397fbe1"
  },
  "reproducibility": {
    "level": "unverified",
    "reason": "input snapshots, output hashes, package locks and platform replay are not captured yet"
  },
  "schema": "ostrin.provenance/v0",
  "verified": false
});
