// Generated by scripts/website-metadata.mjs. Do not edit by hand.
globalThis.OSTRIN_SITE_FACTS = Object.freeze({
  "version": "0.1.0",
  "designDocs": "22",
  "examples": "198",
  "integrationTests": "200",
  "differentialTests": "6",
  "unitTests": "2"
});
