// Generated by scripts/website-metadata.mjs. Do not edit by hand.
globalThis.OSTRIN_SITE_FACTS = Object.freeze({
  "version": "0.1.0",
  "releaseStatus": "published",
  "releaseDate": "2026-09-24",
  "releaseUrl": "https://github.com/sircalch/Ostrin/releases/tag/v0.1.0",
  "designDocs": "25",
  "examples": "264",
  "integrationTests": "243",
  "differentialTests": "6",
  "unitTests": "2"
});
