#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    Ident(String),
    IntLiteral(i64),
    SizedIntLiteral(i128, crate::ast::IntKind),
    FloatLiteral(f64),
    Float32Literal(f32),
    StringLiteral(String),
    CharLiteral(char),

    Fn,
    Mut,
    Return,
    If,
    Else,
    Match,
    For,
    In,
    While,
    Loop,
    Break,
    Continue,
    Trait,
    Impl,
    Record,
    Enum,
    Pub,
    Import,
    As,
    SelfLower,
    SelfUpper,
    Dyn,
    And,
    Or,
    Not,
    Within,
    To,
    Until,
    Step,
    Approximately,
    Tolerance,
    Try,
    Catch,
    Spawn,
    SpawnScope,
    Channel,
    Unit,
    Dimension,
    Define,
    True,
    False,

    Plus,
    Minus,
    Star,
    /// `@`: matrix product (desugared by the parser to `.matmul(...)`).
    At,
    Slash,
    Caret,
    Percent,
    Pipe,
    Amp,

    Eq,
    EqEq,
    NotEq,
    Lt,
    Gt,
    LtEq,
    GtEq,

    Colon,
    ColonColon,
    Comma,
    Dot,
    Arrow,
    FatArrow,
    Underscore,

    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,

    Eof,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub lexeme: String,
    pub line: usize,
    pub col: usize,
    pub newline_before: bool,
}

pub fn keyword_from_str(s: &str) -> Option<TokenKind> {
    use TokenKind::*;
    Some(match s {
        "fn" => Fn,
        "mut" => Mut,
        "return" => Return,
        "if" => If,
        "else" => Else,
        "match" => Match,
        "for" => For,
        "in" => In,
        "while" => While,
        "loop" => Loop,
        "break" => Break,
        "continue" => Continue,
        "trait" => Trait,
        "impl" => Impl,
        "record" => Record,
        "enum" => Enum,
        "pub" => Pub,
        "import" => Import,
        "as" => As,
        "self" => SelfLower,
        "Self" => SelfUpper,
        "dyn" => Dyn,
        "and" => And,
        "or" => Or,
        "not" => Not,
        "within" => Within,
        "to" => To,
        "until" => Until,
        "step" => Step,
        "approximately" => Approximately,
        "tolerance" => Tolerance,
        "try" => Try,
        "catch" => Catch,
        "spawn" => Spawn,
        "spawn_scope" => SpawnScope,
        "channel" => Channel,
        "unit" => Unit,
        "dimension" => Dimension,
        "define" => Define,
        "true" => True,
        "false" => False,
        "_" => Underscore,
        _ => return None,
    })
}
